# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: sektoraler Heilpraktiker Ergotherapie - Fortbildung und Prüfung
tagline: Fortbildung zum sektoralen Heilpraktiker Ergotherapie
fbtitle: Werde jetzt Heilpraktiker für Ergotherapie
fbimage: "https://heilpraktiker-Ergotherapie.com/assets/images/FacebookErfolgreichAlsHPPT.jpg"
email: info@heilpraktiker-Ergotherapie.com    
description: sektoraler Heilpraktiker Ergotherapie - Fortbildung inklusive Prüfung zur Anerkennung nach Aktenlage in NRW, Niedersachsen, Rheinland-Pfalz, Hessen, Baden-Württemberg, Bayern und anderen Bundesländern  
logo: "https://heilpraktiker-Ergotherapie.com/assets/images/LogoHPPT.svg"
logo600jpg: "https://heilpraktiker-Ergotherapie.com/assets/images/LogoHPPT600.jpg"
Bannerjpg: "https://heilpraktiker-Ergotherapie.com/assets/images/BannerHPPT.jpg"
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://heilpraktiker-Ergotherapie.com" # the base hostname & protocol for your site
repository: heilpraktiker-Ergotherapie/


paginate:	10 # The number of posts to show per page on your homepage
paginate_path: '/neuigkeiten-und-lesenswertes-zum-heilpraktiker-Ergotherapie/page:num/'

name: 'Arne Brödel'
bio: Physiotherapeut, Heilpraktiker (Ergotherapie)
author_image: "https//heilpraktiker-Ergotherapie.com/assets/images/author.jpg"
twitter_username: PhysioHP
twitter_url: https://twitter.com/PhysioHP
facebook_url: https://www.facebook.com/HeilpraktikerErgotherapie/
googleplus_url: https://plus.google.com/+HeilpraktikerErgotherapiecom
youtube_url: https://www.youtube.com/c/HeilpraktikerErgotherapiecom

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true
  auto_ids: false
  
#permalink: /neuigkeiten-und-lesenswertes-zum-heilpraktiker-Ergotherapie/:title


plugins:
  - jekyll-paginate
  - jekyll-github-metadata
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap

github: [metadata]
